import React, { useState } from "react";
import Head from "next/head";
import styles from "../styles/Identities.module.css";
import {
  useStarknet,
  useConnectors,
  useStarknetInvoke,
  useStarknetTransactionManager,
} from "@starknet-react/core";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Button from "../components/button";
import ErrorScreen from "../components/errorScreen";
import LoadingScreen from "../components/loadingScreen";
import { useVerifierIdContract } from "../hooks/verifier";
import SuccessScreen from "../components/successScreen";
import { stringToFelt, toFelt } from "../utils/felt";
import Wallets from "../components/wallets";

export default function Twitter() {
  const router = useRouter();
  const [isConnected, setIsConnected] = useState(true);
  const [hasWallet, setHasWallet] = useState(false);

  // Access localStorage
  const isServer = typeof window === "undefined";
  let tokenId;
  if (!isServer) {
    tokenId = window.sessionStorage.getItem("tokenId");
  }

  //Set twitter code
  const [code, setCode] = useState(undefined);
  useEffect(() => {
    setCode(router.query.code);
  }, [router]);

  //Manage Connection
  const { connect, connectors, available } = useConnectors();
  const { account } = useStarknet();

  useEffect(() => {
    if (!account) {
      setIsConnected(false);
    } else {
      setIsConnected(true);
      setScreen("verifyTwitter");
    }
  }, [account]);

  //Server Sign Request
  const [signRequestData, setSignRequestData] = useState(undefined);

  useEffect(() => {
    if (!code || !tokenId) return;

    const requestOptions = {
      method: "POST",
      body: JSON.stringify({
        type: "twitter",
        token_id_low: Number(tokenId),
        token_id_high: 0,
        code: code,
      }),
    };

    fetch("https://verifier.starknet.id/sign", requestOptions)
      .then((response) => response.json())
      .then((data) => setSignRequestData(data));
  }, [code, tokenId]);

  //Contract
  const { contract } = useVerifierIdContract();
  const {
    data: twitterVerificationData,
    invoke,
    error: twitterVerificationError,
  } = useStarknetInvoke({
    contract: contract,
    method: "write_confirmation",
  });
  const { transactions } = useStarknetTransactionManager();

  function verifyTwitter() {
    console.log("sig0", signRequestData.sign0);
    console.log("signRequestData", signRequestData);

    invoke({
      args: [
        [tokenId, 0],
        stringToFelt("twitter"),
        toFelt(signRequestData.user_id),
        [
          signRequestData.sign0,
          signRequestData.sign1,
        ],
      ],
    });
  }

  //Screen management
  const [screen, setScreen] = useState(undefined);

  useEffect(() => {
    for (const transaction of transactions)
      if (transaction.transactionHash === twitterVerificationData) {
        if (transaction.status === "TRANSACTION_RECEIVED") {
          setScreen("loading");
        }
        if (
          transaction.status === "ACCEPTED_ON_L2" ||
          transaction.status === "ACCEPTED_ON_L1"
        ) {
          setScreen("success");
        }
      }
  }, [twitterVerificationData, transactions]);

  // Error Management
  useEffect(() => {
    if (signRequestData?.status === "error" || twitterVerificationError) {
      console.log("twitterVerificationError", twitterVerificationError);
      setScreen("error");
    }
  }, [twitterVerificationError, signRequestData]);

  const errorScreen = isConnected && screen === "error";

  return (
    <div className="h-screen w-screen">
      <Head>
        <title>Starknet.id</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/starknet-logo.webp" />
      </Head>

      <div className={styles.container}>
        {!isConnected &&
          connectors.map((connector) =>
            connector.available() && connector.options.id === "argent-x" ? (
              <>
                {hasWallet ? (
                  <Wallets close={() => setHasWallet(false)} />
                ) : null}
                <h1 className="sm:text-5xl text-5xl">
                  You need to connect anon
                </h1>
                <div className="mt-8">
                  <Button
                    onClick={() =>
                      available.length === 1
                        ? connect(available[0])
                        : setHasWallet(true)
                    }
                  >
                    Connect Wallet
                  </Button>
                </div>
              </>
            ) : null
          )}
        {screen === "loading" && <LoadingScreen />}
        {errorScreen && (
          <ErrorScreen
            onClick={() => router.push(`/identities/${tokenId}`)}
            errorButton="Retry to connect"
          />
        )}
        {screen === "success" && (
          <>
            <SuccessScreen
              onClick={() => router.push(`/identities/${tokenId}`)}
              successButton="Get back to your starknet identity"
              successMessage="What a chad, your twitter is verified!"
            />
            {/* <p className="mt-2">
              <a
                className="footerLink"
                href={`https://alpha4.starknet.io/feeder_gateway/get_transaction_receipt?transactionHash=${verifyData?.txid}`}
              >
                Check your transaction state
              </a>
            </p> */}
          </>
        )}
        {screen === "verifyTwitter" && (
          <>
            <h1 className="sm:text-5xl text-5xl mt-4">
              It&apos;s time verify your twitter on chain !
            </h1>
            <div className="mt-8">
              <Button onClick={verifyTwitter}>Verify my Twitter</Button>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
